cogs/admin.py
Per Gelgoog's request. Also added \tr as an additional alias (in addition to already existing \latency and \trace).
=> Formatting tweaks for \latency

cogs/admin.py, cogs/events.py, cogs/general.py
Allow min and max time increments in restartshadow
Also fix data center name in latency
Add task to automatically update status in #known-issues
=> Edit commands and add task

cogs/general.py
updated wording on minimum requirements, and data center tours
=> ltt and minreq update

cogs/general.py
This might break some things but should all work - Test time.
=> Deduplicate general

cogs/admin.py, docs/README.md
Add Github pages area/fix gitref for cat
=> Add GitHub documentation structure, fix gitref for cat

cogs/general.py
- update account page file
- add reset quick command
- update apple tv app command
- add ios command
- minor text formatting on support command
=> Account page update

.idea/sqldialects.xml, cogs/general.py
Update Account page links and re-work account commands to use text_command_helper
=> Update Account pages links.

.gitignore, .vscode/settings.json, cogs/events.py, cogs/general.py, requirements.txt
=> Alpha command and event

.gitignore, cogs/general.py
=> added applications update

cogs/general.py
Also rename apps command to stable and replace existing alias list
with just official
=> Add docstrings and beta command

cogs/web.py
=> Test #3. Web cog

bot.py, cogs/web.py
Some tweaks and changes to web cog.
=> Web testing

cogs/web.py
=> Process out payload.

cogs/web.py
=> Improve Event handling.

cogs/web.py
=> Hmm can't read action... check.

cogs/web.py
=> Remove Debug call and fix content to payload

cogs/admin.py
Add Code Approvers as authorized to reload cogs, gitref, and shutdown
=> add @justathoughtor2 as an authorized user

cogs/general.py
=> Added errata per @LEQUI000

cogs/events.py, cogs/general.py
Updated channel ID in general to reflect the new community-help channel. Updated link in events to redirect to the official known issues page instead of the dead article link.
=> Minor fixes

cogs/general.py
=> Update Microphone link

cogs/events.py
Not like Valorant where the mere mention of the game makes Rexford go off. Less annoying.
=> Added Halo Infinite crash trigger

cogs/events.py
=> Fixed spacing

cogs/general.py
=> if I have to modify one more thing I am going to become an alcohol

cogs/events.py, cogs/general.py
Corrected a lot of stuff. Added Genshin autoresponder.
=> Higher level coding

cogs/admin.py, cogs/database.py
Updated Role names. Please don't break
=> Shadow Expert hotfix
